dev: true
title: move86go
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
lang: go
enablerun: true
action:
  before:
    - gofmt -w ./
  after:
    - ps -ef|grep 'move86go service'| grep -v grep | awk '{print $2}' | xargs kill -9
    - ./move86go service &
  exit:
    - ps -ef|grep 'move86go service'| grep -v grep | awk '{print $2}' | xargs kill -9
    - rm -rf ./move86go
link: https://github.com/midoks/zzz
