dev: true
title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- templates
ext:
- go
lang: go
enablerun: true
action:
  before:
    - gofmt -w ./
  after:
    - echo "zzz end"
  exit:
    - echo "exit"
link: https://github.com/midoks/zzz
